export const GET_SAVED_FORMS = 'FORM/GET_SAVED_FORMS';
export const UPDATE_CONSTRUCTOR = 'FORM/UPDATE_CONSTRUCTOR';
export const SET_CURRENT_FORM = 'FORM/SET_CURRENT_FORM';
export const SET_PREVIEW = 'FORM/SET_PREVIEW';

export const SET_LOGGED_IN_STATUS = 'HEADER_SIDEBAR/SET_LOGGED_IN_STATUS';
