export const GET_SAVED_FORMS = 'CONSTRUCTOR/GET_SAVED_FORMS';
export const UPDATE_ADDED_ELEMENTS = 'CONSTRUCTOR/UPDATE_ADDED_ELEMENTS';
export const SET_CURRENT_FORM = 'CONSTRUCTOR/SET_CURRENT_FORM';
export const SET_PREVIEW = 'CONSTRUCTOR/SET_PREVIEW';
export const UPDATE_STATUS = 'CONSTRUCTOR/UPDATE_STATUS';
export const SET_SEARCH_INPUT = 'CONSTRUCTOR/SET_SEARCH_INPUT';

export const SET_LOGGED_IN_STATUS = 'HEADER_SIDEBAR/SET_LOGGED_IN_STATUS';
