export const SORT_ELEMENTS = 'FORM/SORT_ELEMENTS';
export const ADD_ELEMENT = 'FORM/ADD_ELEMENT';
export const LABLE_CHANGE = 'FORM/LABLE_CHANGE';
export const VALUE_CHANGE = 'FORM/VALUE_CHANGE';
export const REMOVE_ELEMENT = 'FORM/REMOVE_ELEMENT';
export const SET_REQUIRED = 'FORM/SET_REQUIRED';
export const RANGE_CHANGE_MINIMUM = 'FORM/RANGE_CHANGE_MINIMUM';
export const RANGE_CHANGE_MAXIMUM = 'FORM/RANGE_CHANGE_MAXIMUM';
export const GET_SAVED_FORMS = 'FORM/GET_SAVED_FORMS';
export const UPDATE_CONSTRUCTOR = 'FORM/UPDATE_CONSTRUCTOR';

export const SET_LOGGED_IN_STATUS = 'HEADER_SIDEBAR/SET_LOGGED_IN_STATUS';

export const CHANGE_TITLE = 'CUSTOM_FORM/CHANGE_TITLE';
export const CHANGE_FORM_TITLE = 'CUSTOM_FORM/CHANGE_FORM_TITLE';
export const CHANGE_FORM_SUBTITLE = 'CUSTOM_FORM/CHANGE_FORM_SUBTITLE';
export const CHANGE_CUSTOM_INPUTS_VALUES =
    'CUSTOM_FORM/CHANGE_CUSTOM_INPUTS_VALUES';
