export const UPDATE_PASSWORD = 'CHANGE_PASSWORD/UPDATE_PASSWORD';
export const UPDATE_PASSWORD_ERROR = 'CHANGE_PASSWORD/UPDATE_PASSWORD_ERROR';
export const UPDATE_REPEAT_PASSWORD = 'CHANGE_PASSWORD/UPDATE_REPEAT_PASSWORD';
export const UPDATE_REPEAT_PASSWORD_ERROR =
    'CHANGE_PASSWORD/UPDATE_REPEAT_PASSWORD_ERROR';
export const SET_IS_VALID = 'CHANGE_PASSWORD/SET_IS_VALID';
export const RESET_FORM = 'CHANGE_PASSWORD/RESET_FORM';
