export const UPDATE_EMAIL = 'LOGIN/UPDATE_EMAIL';
export const UPDATE_EMAIL_ERROR = 'LOGIN/UPDATE_EMAIL_ERROR';
export const UPDATE_PASSWORD = 'LOGIN/UPDATE_PASSWORD';
export const UPDATE_PASSWORD_ERROR = 'LOGIN/UPDATE_PASSWORD_ERROR';
export const SET_IS_VALID = 'LOGIN/SET_IS_VALID';
export const RESET_FORM = 'LOGIN/RESET_FORM';
