export const UPDATE_EMAIL = 'REGISTER/UPDATE_EMAIL';
export const UPDATE_EMAIL_ERROR = 'REGISTER/UPDATE_EMAIL_ERROR';
export const UPDATE_PASSWORD = 'REGISTER/UPDATE_PASSWORD';
export const UPDATE_PASSWORD_ERROR = 'REGISTER/UPDATE_PASSWORD_ERROR';
export const UPDATE_REPEAT_PASSWORD = 'REGISTER/UPDATE_REPEAT_PASSWORD';
export const UPDATE_REPEAT_PASSWORD_ERROR =
    'REGISTER/UPDATE_REPEAT_PASSWORD_ERROR';
export const SET_IS_VALID = 'REGISTER/SET_IS_VALID';
export const RESET_FORM = 'REGISTER/RESET_FORM';
