export const UPDATE_FILTER_CHARS = 'SEND_FORM_POPUP/UPDATE_FILTER_CHARS';
export const UPDATE_ERROR_MESSAGE = 'SEND_FORM_POPUP/UPDATE_ERROR_MESSAGE';
export const SET_OPEN_STATUS = 'SEND_FORM_POPUP/SET_OPEN_STATUS';
export const UPDATE_SELECTED_SCHOOLS =
    'SEND_FORM_POPUP/UPDATE_SELECTED_SCHOOLS';
export const SET_SELECTED_FORM = 'SEND_FORM_POPUP/SET_SELECTED_FORM';
