export const SET_OPEN_STATUS = 'STATUS_POPUP/SET_OPEN_STATUS';
export const UPDATE_STATUS_TEXT = 'STATUS_POPUP/UPDATE_STATUS_TEXT';
export const UPDATE_STATUS_CODE = 'STATUS_POPUP/UPDATE_STATUS_CODE';
