export const SET_HANDBOOK_POPUP = 'USER_HANDBOOK/SET_HANDBOOK_POPUP';
export const SET_NEW_HANDBOOK_NOTE = 'USER_HANDBOOK/SET_NEW_HANDBOOK_NOTE';
export const ADD_NOTES_TO_HANDBOOK = 'USER_HANDBOOK/ADD_NOTES_TO_HANDBOOK';
export const RESET_HANDBOOK_POPUP = 'USER_HANDBOOK/RESET_HANDBOOK_POPUP';
export const SET_HANDBOOK_NOTE = 'USER_HANDBOOK/SET_HANDBOOK_NOTE';
export const SET_IS_VALID = 'USER_HANDBOOK/SET_IS_VALID';
export const UPDATE_PLACEHOLDER_ERROR =
    'USER_HANDBOOK/UPDATE_PLACEHOLDER_ERROR';
export const UPDATE_VALUE_ERROR = 'USER_HANDBOOK/UPDATE_VALUE_ERROR';
export const SET_IS_EDIT = 'USER_HANDBOOK/SET_IS_EDIT';
export const UPDATE_HANDBOOK_FILTER = 'USER_HANDBOOK/UPDATE_HANDBOOK_FILTER';
