export const UPDATE_CREATE_TITLE = 'USER_CONSTRUCTOR/UPDATE_CREATE_TITLE';
export const UPDATE_CREATE_SUBTITLE = 'USER_CONSTRUCTOR/UPDATE_CREATE_SUBTITLE';
export const SET_IS_VALID = 'USER_CONSTRUCTOR/SET_IS_VALID';
export const UPDATE_ELEMENTS = 'USER_CONSTRUCTOR/UPDATE_ELEMENTS';
export const SET_IS_OPEN = 'USER_CONSTRUCTOR/SET_IS_OPEN';
export const RESET_CREATE = 'USER_CONSTRUCTOR/RESET_CREATE';

export const UPDATE_FILTER_CHARS = 'USER_CONSTRUCTOR/UPDATE_FILTER_CHARS';
export const UPDATE_FILTER_ACCESS = 'USER_CONSTRUCTOR/UPDATE_FILTER_ACCESS';
export const UPDATE_FILTER_TABS = 'USER_CONSTRUCTOR/UPDATE_FILTER_TABS';
