export const SET_HANDBOOK_POPUP = 'USER_HANDBOOK/SET_HANDBOOK_POPUP';
export const SET_HANDBOOK_NOTE = 'USER_HANDBOOK/SET_HANDBOOK_NOTE';
export const ADD_NOTES_TO_HANDBOOK = 'USER_HANDBOOK/ADD_NOTES_TO_HANDBOOK';
