export const UPDATE_INSTITUTION_PARAMS =
    'USER_PROFILE/UPDATE_INSTITUTION_PARAMS';
export const UPDATE_PROFILE_INFO = 'USER_PROFILE/UPDATE_PROFILE_INFO';
export const UPDATE_POPUP = 'USER_PROFILE/UPDATE_POPUP';
export const RESET_POPUP = 'USER_PROFILE/RESET_POPUP';
