export const UPDATE_FILTER_CHARS = 'USER_CONSTRUCTOR/UPDATE_FILTER_CHARS';
export const UPDATE_FILTER_ACCESS = 'USER_CONSTRUCTOR/UPDATE_FILTER_ACCESS';
export const UPDATE_FILTER_TABS = 'USER_CONSTRUCTOR/UPDATE_FILTER_TABS';
