export const UPDATE_INSTITUTION_PARAMS =
    'USER_PROFILE/UPDATE_INSTITUTION_PARAMS';
export const UPDATE_PROFILE_INFO = 'USER_PROFILE/UPDATE_PROFILE_INFO';
export const UPDATE_POPUP = 'USER_PROFILE/UPDATE_POPUP';
export const UPDATE_CHANGE_DATA = 'USER_PROFILE/UPDATE_CHANGE_DATA';
export const RESET_DATA_CHANGING = 'USER_PROFILE/RESET_DATA_CHANGING';
export const CHANGE_PROFILE_PASSWORD = 'USER_PROFILE/CHANGE_PROFILE_PASSWORD';
export const UPDATE_VALIDATION_INPUT = 'USER_PROFILE/UPDATE_VALIDATION_INPUT';
export const UPDATE_VALIDATION_CASES = 'USER_PROFILE/UPDATE_VALIDATION_CASES';
