export const UPDATE_INSTITUTION_PARAMS =
    'USER_PROFILE/UPDATE_INSTITUTION_PARAMS';
export const UPDATE_PROFILE_INFO = 'USER_PROFILE/UPDATE_PROFILE_INFO';
export const UPDATE_POPUP = 'USER_PROFILE/UPDATE_POPUP';
export const SET_POPUP_TITLE = 'USER_PROFILE/SET_POPUP_TITLE';
export const UPDATE_CHANGE_DATA = 'USER_PROFILE/UPDATE_CHANGE_DATA';
